name: Push pages to pages

on:
  push:
    branches-ignore:
      - pages

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  push-directory-to-pages:
    runs-on: ubuntu-latest
    steps:
    # Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Ensure you are on the correct branch
    - name: Get the branch name
      run: |
        echo "Pushed from branch: ${{ github.ref_name }}"

    # Copy the directory based on the branch
    - name: Copy directory based on branch
      run: |
        cp -r pages temppages

    # Commit and push changes to 'pages' branch
    - name: Copy changes to pages branch
      run: |
        git checkout pages
        if [[ "${{ github.ref_name }}" == "master" ]]; then
          echo "Copying from master location to pages branch"
          cp -r temppages/* ghpages/.
        else
          echo "Copying from other branches location to pages branch"
          cp -r temppages "ghpages/${{github.ref_name}}"
        fi
        git config --global user.email "autopages@keybard.svalboard.app"
        git config --global user.name "AutoPages"
        echo hi > pages/foot
        git add pages
        git commit -am "Update from ${{ github.ref_name }}"
        git push
        rm -rm temppages ghpages

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'pages'

    # Deploy to github pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
